### ISSUE TITLE
fix precision problems

### ISSUE THREAD

**Issue by gpmn** [bitfinexcom/bitfinex-api-go#142]
Hi,
    I got such error message, I suppose it's better to change at here.

2018/12/27 08:24:03 jenny.go:467: DayBreak.createPosition - s.egn.SubmitSingleOrder(xxxxxxxxxxxxxx, ETCUSD, 174.33776, 5.73599, "limit") failed: POST https://api.bitfinex.com/v1/order/new: 400 Invalid order price precision (5 sig figures limit)

diff --git a/v1/orders.go b/v1/orders.go
index a26f5ec..2c4f135 100644
--- a/v1/orders.go
+++ b/v1/orders.go
@@ -86,8 +86,8 @@ func (s *OrderService) Create(symbol string, amount float64, price float64, orde

payload := map[string]interface{}{  
 		"symbol":   symbol,  
		**"amount":   strconv.FormatFloat(amount, 'f', -1, 32),  
		"price":    strconv.FormatFloat(price, 'f', -1, 32),**  
 		"side":     side,  
 		"type":     orderType,  
 		"exchange": "bitfinex",  

change to ====>>>>   
		"amount":   strconv.FormatFloat(amount, 'g', 5, 32),   
		"price":    strconv.FormatFloat(price, 'g', 5, 32),

**Comment by andreygrehov** [comment]
You are using v1 api, which is deprecated. Consider migrating to v2.

**Comment by JacobPlaster** [comment]
Closing as V1, V2 is now considered stable so please migrate. Thanks!
