### ISSUE TITLE
v2: DepositAddress and CreateDepositAddress do not work

### ISSUE THREAD

**Issue by andreygrehov** [bitfinexcom/bitfinex-api-go#202]
#### Issue type
- [x] bug
- [ ] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description
`NotifyInfo` is `nil`

#### Steps to reproduce
```
package main

import (
	"fmt"

	"github.com/bitfinexcom/bitfinex-api-go/v2/rest"
)

func main() {
	key := "<KEY>"
	secret := "<SECRET>"
	r := rest.NewClient().Credentials(key, secret)
	n, err := r.Wallet.DepositAddress("exchange", "bitcoin")
	if err != nil {
		panic(err)
	}
	fmt.Println(n.NotifyInfo)
}
```

**Comment by JacobPlaster** [comment]
Nice spot @andreygrehov - fixed in https://github.com/bitfinexcom/bitfinex-api-go/pull/203 please review when you get the chance

**Comment by andreygrehov** [comment]
Resolved. Thank you, Jacob.
