### ISSUE TITLE
Trade execution update parsing error

### ISSUE THREAD

**Issue by dnfd** [bitfinexcom/bitfinex-api-go#220]
#### Issue type
- [x] bug
- [ ] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description
Looks like trade execution update has one additional field now, lib does not parse this event anymore.

This one expected
```
[0,"tu",[402088407,"tETHUST",1574963975602,34938060782,-0.2,153.57,"MARKET",0,-1,-0.061668,"USD"]]
```

This one I get now
```
[0,"tu",[500513817,"tCHZUSD",1599145405293,50261323849,356,0.015955,"EXCHANGE FOK",0.017238,-1,-0.712,"CHZ",1599145405]]
```
#### Steps to reproduce
- Do any trade and you get this error
```
&errors.errorString{s:"data slice too short for trade update: []interface {}{5.00513817e+08, \"tCHZUSD\", 1.599145405293e+12, 5.0261323849e+10, 356, 0.015955, \"EXCHANGE FOK\", 0.017238, -1, -0.712, \"CHZ\", 1.599145405e+09}"} component=engine-bitfinex
```

##### Additional Notes:
- Also error is misleading, actual slice is too long in this case.

**Comment by JacobPlaster** [comment]
Hey @dnfd, this was fixed in https://github.com/bitfinexcom/bitfinex-api-go/pull/222 (v3.0.1)
