### ISSUE TITLE
Ho do I install?

### ISSUE THREAD

**Issue by zdavatz** [bitfinexcom/bitfinex-api-go#23]
Hi

How do I install this software?

I am doing
```
~/.software/bitfinex-api-go> go generate
```
then
```
~/.software/bitfinex-api-go> go install
```
and then I get
```
websocket.go:13:5: cannot find package "github.com/gorilla/websocket" in any of:
        /usr/lib/go/src/github.com/gorilla/websocket (from $GOROOT)
        ($GOPATH not set)
```

**Comment by erubboli-bfx** [comment]
Please ensure you follow the default directory organization (in `~/go` the directory) or set a GOPATH environment variable (see: https://golang.org/cmd/go/#hdr-GOPATH_environment_variable).

In order to download dependencies you should use `go get` command.

**Comment by zdavatz** [comment]
ok, thanks!

**Comment by BVV13** [comment]
go get github.com/bitfinexcom/bitfinex-api-go  
and then I get:
can`t load package: package github.com/bitfinexcom/bitfinex-api-go: no Go files in D:\My\src\github.com/bitfinexcom/bitfinex-api-go
