### ISSUE TITLE
nonce, claim

### ISSUE THREAD

**Issue by malaschitz** [bitfinexcom/bitfinex-api-go#32]
1. Nonce is not properly generated. Nonce must be always higher and higher number. There is my own implementation: https://github.com/malaschitz/bitfinex-api-go/blob/master/utils/nonce.go

2. Second problem is with claim. Function claim in positions.go send position_id as string. It is wrong and bitfinex return error: position_id must be integer. 

3. But worst problem, when I change properly claim function, api do not return any response. There is probably some bug directly in API of bitfinex. I am not able claim my position and there is not other possibility.

**Comment by erubboli-bfx** [comment]
@malaschitz you're right, didn't notice `nonce` generation has been changed. 
Do you want to submit a PR ? 
I'm currently investigating the claim issue.

**Comment by malaschitz** [comment]
There is possible workaround with claim. Instead of claim I could send order with the same amount: SELL instead of BUY and BUY instead of SELL.

**Comment by erubboli-bfx** [comment]
@malaschitz we're fixing the endpoint, should be in production soon.  But the workaround should work in the meantime.

**Comment by malaschitz** [comment]
Great work !!

**Comment by addodelgrossi** [comment]
@malaschitz Did you solve the problem, does not the error happen anymore? What operating system are you using? I'm having the same problem, on linux less often, already on Mac OS all the time.

Thanks

**Comment by jvatianou** [comment]
closing since seemingly the bug has also been closed.  if not, let me know of any feedback.
