### ISSUE TITLE
issues installing the package. 

### ISSUE THREAD

**Issue by tensor-programming** [bitfinexcom/bitfinex-api-go#46]
when i run go get github.com/bitfinexcom/bitfinex-api-go i get an error that says there are no buildable source files in the directory.  I've tried running go get github.com/bitfinexcom/bitfinex-api-go/utils which works fine, but go get github.com/bitfinexcom/bitfinex-api-go/bitfinex does not work.  obviously I am missing something here.  Anyone got any ideas? 

Edit:

Never mind, I figured it out.  its go get github.com/bitfinexcom/bitfinex-api-go/v1.  You should update the documentation to reflect this.

**Comment by kev111** [comment]
yeah that's right! thx for the help

**Comment by icolwell** [comment]
PR #41 updates the readme. Hopefully someone with write access can merge it.

**Comment by hantuzun** [comment]
This issue could be closed.
