### ISSUE TITLE
Nonce is too small 

### ISSUE THREAD

**Issue by alehano** [bitfinexcom/bitfinex-api-go#6]
Sometimes I get this error
```
400 Nonce is too small.
```

**Comment by prdn** [comment]
Merged your PR

**Comment by malaschitz** [comment]
I have the same bug.

**Comment by addodelgrossi** [comment]
I have the same problem, in my case, if running using linux ubuntu it's good, but, in the mac os I have the same problem.

The parameters it's the same in two cases.

Any idea ?
