### ISSUE TITLE
v2: Wrong endpoints

### ISSUE THREAD

**Issue by utdrmac** [bitfinexcom/bitfinex-api-go#91]
Attempting to use example v2:

```
2018/02/09 15:25:40 getting orders: POST https://api.bitfinex.com/v2/orders/tIOTBTC/hist: 404 Error decoding response error message. Please see response body for more information. (0)
```

Documentation says path should be this `/auth/r/orders/tBTCUSD/hist`
Probably others that have this wrong too.

**Comment by mlensment** [comment]
+1

**Comment by brobits** [comment]
this branch has updated authentication for v2 REST & corrected URI endpoints: https://github.com/brobits/bitfinex-api-go/commit/8b19f0dafc7a213f1dc6598b65855b4701b75b3b
