### ISSUE TITLE
v2: REST Codebase doesn't send API Key/Signature headers

### ISSUE THREAD

**Issue by utdrmac** [bitfinexcom/bitfinex-api-go#92]
Been reading for an hour trying to find in the codebase in the REST where bfx-nonce, bfx-apikey, and bfx-signature are set. Simple grep of "apikey" reveals no results. So there's no code sending API credentials, which means the example client provided fails to execute.

**Comment by brobits** [comment]
can you pull this branch and try again? https://github.com/brobits/bitfinex-api-go/tree/maintenance
